title: 迭代
email: dongmeilianghy@sina.com
description: 持续迭代，终得正解。
baseurl: "/"
url: "http://DamianSheldon.github.io"
twitter_username: dongmeilianghy
github_username: DamianSheldon

subtitle: Here's where it all happens for me.
author: Sheldon
simple_search: https://www.bing.com/search
keywords: iOS, Objective-C, Swift, Xcode, Java, Android, Web, HTML, Javascript, CSS, English

date_format: "ordinal"
subscribe_rss: /atom.xml

plugins:
  - jekyll-feed
  - jekyll-seo-tag

permalink: /blog/:title.html

# Google Analytics
google_analytics: G-YPLKXV8RKB
